server:
  port: 1000

#These values will be changed by docker when through params
services:
  hosts:
    auth: localhost
    jwt: localhost
    project: localhost
    projectrule: localhost
  ports:
    auth: 2000
    jwt: 3000
    project: 4000
    projectrule: 5000

